### ISSUE TITLE
WX-010 not properly detected

### ISSUE THREAD

**Issue by cabletie** [jalmeroth/pymusiccast#14]
hassio fails to pick up info from http://192.168.86.20:80/YamahaRemoteControl/desc.xml - URL doesn't seem to exist on device:

`Unsupported Yamaha device? Failed to fetch http://192.168.86.20:80/YamahaRemoteControl/desc.xml`

Initial data it uses (and sorry I don't know where it gets this from initially - my python foo is not that good):
`{
    "host": "192.168.86.20",
    "port": 49154,
    "ssdp_description": "http://192.168.86.20:49154/MediaRenderer/desc.xml",
    "name": "Yamaha Airplay",
    "model_name": "WX-010",
    "model_number": "010",
    "serial": "REDACTED",
    "manufacturer": "Yamaha Corporation",
    "udn": "uuid:9a-redacted-d2",
    "upnp_device_type": "urn:schemas-upnp-org:device:MediaRenderer:1",
    "control_url": "http://192.168.86.20:80/YamahaRemoteControl/ctrl",
    "description_url": "http://192.168.86.20:80/YamahaRemoteControl/desc.xml"
}`

It does get a response from http://192.168.86.20:49154/MediaRenderer/desc.xml I assume because I can go get it myself:
`<?xml version="1.0" encoding="utf-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:yamaha="urn:schemas-yamaha-com:device-1-0">
    <specVersion>
        <major>1</major>
        <minor>0</minor>
    </specVersion>
    <device>
        <dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
        <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
        <friendlyName>Yamaha Family Room Airplay</friendlyName>
        <manufacturer>Yamaha Corporation</manufacturer>
        <manufacturerURL>http://www.yamaha.com/</manufacturerURL>
        <modelDescription>MusicCast</modelDescription>
        <modelName>WX-010</modelName>
        <modelNumber>010</modelNumber>
        <modelURL>http://www.yamaha.com/</modelURL>
        <serialNumber>REDACTED</serialNumber>
        <UDN>uuid:9a-redacted-d2</UDN>
        <iconList>
            <icon>
                <mimetype>image/jpeg</mimetype>
                <width>48</width>
                <height>48</height>
                <depth>24</depth>
                <url>/Icons/48x48.jpg</url>
            </icon>
            <icon>
                <mimetype>image/jpeg</mimetype>
                <width>120</width>
                <height>120</height>
                <depth>24</depth>
                <url>/Icons/120x120.jpg</url>
            </icon>
            <icon>
                <mimetype>image/png</mimetype>
                <width>48</width>
                <height>48</height>
                <depth>24</depth>
                <url>/Icons/48x48.png</url>
            </icon>
            <icon>
                <mimetype>image/png</mimetype>
                <width>120</width>
                <height>120</height>
                <depth>24</depth>
                <url>/Icons/120x120.png</url>
            </icon>
        </iconList>
        <serviceList>
            <service>
                <serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
                <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
                <SCPDURL>/AVTransport/desc.xml</SCPDURL>
                <controlURL>/AVTransport/ctrl</controlURL>
                <eventSubURL>/AVTransport/event</eventSubURL>
            </service>
            <service>
                <serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
                <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
                <SCPDURL>/RenderingControl/desc.xml</SCPDURL>
                <controlURL>/RenderingControl/ctrl</controlURL>
                <eventSubURL>/RenderingControl/event</eventSubURL>
            </service>
            <service>
                <serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
                <serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
                <SCPDURL>/ConnectionManager/desc.xml</SCPDURL>
                <controlURL>/ConnectionManager/ctrl</controlURL>
                <eventSubURL>/ConnectionManager/event</eventSubURL>
            </service>
        </serviceList>
        <presentationURL>http://192.168.86.20/</presentationURL>
    </device>
    <yamaha:X_device>
        <yamaha:X_URLBase>http://192.168.86.20:80/</yamaha:X_URLBase>
        <yamaha:X_serviceList>
            <yamaha:X_service>
                <yamaha:X_specType>urn:schemas-yamaha-com:service:X_YamahaRemoteControl:1</yamaha:X_specType>
                <yamaha:X_controlURL>/YamahaRemoteControl/ctrl</yamaha:X_controlURL>
                <yamaha:X_unitDescURL>/YamahaRemoteControl/desc.xml</yamaha:X_unitDescURL>
            </yamaha:X_service>
            <yamaha:X_service>
                <yamaha:X_specType>urn:schemas-yamaha-com:service:X_YamahaExtendedControl:1</yamaha:X_specType>
                <yamaha:X_yxcControlURL>/YamahaExtendedControl/v1/</yamaha:X_yxcControlURL>
                <yamaha:X_yxcVersion>1145    </yamaha:X_yxcVersion>
            </yamaha:X_service>
        </yamaha:X_serviceList>
    </yamaha:X_device>
</root>`

But then fails with this in the logs:
`2019-04-26 23:24:37 INFO (SyncWorker_9) [homeassistant.loader] Loaded yamaha from homeassistant.components.yamaha
2019-04-26 23:24:37 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.yamaha
2019-04-26 23:24:37 ERROR (SyncWorker_10) [rxv] Unsupported Yamaha device? Failed to fetch http://192.168.86.20:80/YamahaRemoteControl/desc.xml
2019-04-26 23:24:37 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform yamaha
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/yamaha/media_player.py", line 81, in setup_platform
    unit_desc_url=desc_url).zone_controllers()
  File "/usr/local/lib/python3.7/site-packages/rxv/rxv.py", line 392, in zone_controllers
    for zone in self.zones():
  File "/usr/local/lib/python3.7/site-packages/rxv/rxv.py", line 383, in zones
    xml = self._desc_xml
AttributeError: 'RXV' object has no attribute '_desc_xml'`

Thought you might like to know.

**Comment by jalmeroth** [comment]
There are currently two components targeting Yamaha devices. Since you are using the other one, you might want to address this issue [here](https://github.com/wuub/rxv) or re-check your configuration for this component [here](https://www.home-assistant.io/components/yamaha_musiccast/).
