### ISSUE TITLE
Show offline devices

### ISSUE THREAD

**Issue by runningman84** [jalmeroth/pymusiccast#9]
I have an AVR which is normally without power if nobody is in the living room. It would be cool if your module would just retry "forever" until it finds configured devices. Maybe you can add an option to suppress any connection errors and just show these devices as offline.

**Comment by jalmeroth** [comment]
Hm, this is an _interesting_ use case. Do you think this is something one could archive using [Discovery](https://home-assistant.io/developers/component_discovery/)/[NetDisco](https://github.com/home-assistant/netdisco)? Could you try to find out the specifics?

**Comment by runningman84** [comment]
From my point of view discovery/netdisco would not help very much here. Because in my case I have configured these devices statically like this:

- platform: yamaha_musiccast
  host: 192.168.178.xxx
  name: Yamaha WX-030 Box
  port: 5555
- platform: yamaha_musiccast
  host: 192.168.178.yyy
  name: Yamaha RX-V481 AVR
  port: 5556

My implementation just assumed the device as STATE_OFF. 
See line 126:
https://gist.github.com/runningman84/5464ec4dc39b10efd10828ca7cef25d0

**Comment by jalmeroth** [comment]
Well, actually I think this will not work here. pymusiccast queries Zone-information to setup the linked devices. Its also establishing a UDP-connection to receive live-events from your device. If the device is turned off, we can not establish the connection or finish the setup properly.

**Comment by runningman84** [comment]
yes but you could keep it in an offline state until it gets up?

**Comment by jalmeroth** [comment]
No, because I can't set it up properly. And my interpretation of good HASS-behaviour is that we shouldn't poll indefinitely to finish device setup.

**Comment by jalmeroth** [comment]
… and even if, how do I get notified that the device got up?

**Comment by runningman84** [comment]
hmm my device_tracker sensor could tell you...

**Comment by jalmeroth** [comment]
I think your request is getting a bit too far here. If you are able to provide a pull-request that solves this issue, I will be happy to accept it.

**Comment by jalmeroth** [comment]
@runningman84 FYI: https://github.com/home-assistant/home-assistant/pull/10258#issuecomment-341156575
